### ISSUE TITLE
Add useradd option

### ISSUE THREAD

**Issue by AnninoDr4** [RandomCoderOrg/udroid-extra-tool-proot#7]
this is already documented but adding an option to create and fix new user will make this process less painfull

Possible options
```
* --useradd [ TYPE ( --nopasswd | --passwd ) ] <username> <password>
```

<hr>

possible extra features
- Apply theme on new user add

###### Need to figure out lot of variables

**Comment by SaicharanKandukuri** [comment]
A little change for the command-line options
```
* [ -u | --user | --username ] <username> [ -p | --passwd | --password ] <password> [options]
```
with only one option `--nopasswd`

**Comment by SaicharanKandukuri** [comment]
- [ ] add feature to clone theme

**Comment by AnninoDr4** [comment]
Clone is a bad idea cause who knows what kind of third party apps/lib they use to extra rice desktop
> So just use udroid default theming

**Comment by SaicharanKandukuri** [comment]
theme clone for later
